### ISSUE TITLE
Extension output in <section>

### ISSUE THREAD

**Issue by JetGum** [GiovanniSalmeri/yellow-link#1]
Hello Giovanni,

a quick question that applies to both your (old) selflink and (newer) yellow-link extension.

The frontend only displays the literal [a slug - "Anchor text"], but does not transform into a clickable link, if I place the shortcode into a piece of code like this:

`<section><details><summary>How can I make selflink/link work in Yellow?</summary><p>Read more about [a how-to-use selflink - "How to use Selflink extension"]</p></details></section>`

Output: 
![image](https://github.com/GiovanniSalmeri/yellow-link/assets/48367334/3faa22b2-a8ff-4f3d-8d9c-8b95ad91de35)

Am I missing something?

Cheers, Carsten

**Comment by GiovanniSalmeri** [comment]
Hello Carsten! The [markdown parser](https://github.com/annaesvensson/yellow-markdown) does not translate in HTML the content of a block element unless there is a `markdown="1"` attribute. This is true also for shortcodes, since they are handled by the (Yellow extended) markdown parser. The solution is therefore simple:

`<section><details><summary>How can I make selflink/link work in Yellow?</summary><p markdown="1">Read more about [a how-to-use selflink - "How to use Selflink extension"]</p></details></section>`

This should work also with the [Parsedown parser](https://github.com/annaesvensson/yellow-parsedown), but I have not checked.

**Comment by JetGum** [comment]
Dear Giovanni,

ah, yes, of course. It's the parser, and I can confirm it works.

Thanks for pointing me in the right direction!

Cheers, Carsten
